font:
  normal:
    family: 'Cascadia Code'
    style: Regular
  bold:
    family: 'Cascadia Code'
    style: Bold
  italic:
    family: 'Cascadia Code'
    style: Italic
  bold_italic:
    family: 'Cascadia Code'
    style: Bold Italic
  size: 12.0

draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: '#32302f'
    foreground: '#f2e5bc'

  normal:
    black:   '#6a6766'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#f2e5bc'

  bright:
    black:   '#1d2021'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#83c07c'
    white:   '#fff1c6'

background_opacity: .95

cursor:
  style:
    shape: Underline
    blinking: On
  vi_mode_style: Block

mouse:
  hide_when_typing: true

mouse_bindings:
  - { mouse: Right, action: PasteSelection }

# key_bindings:
  #- { key: V,              mods: Control|Shift, mode: ~Vi,        action: Paste            }
  #- { key: C,              mods: Control|Shift,                   action: Copy             }
  #- { key: Key0,           mods: Control,                         action: ResetFontSize    }
  #- { key: Equals,         mods: Control,                         action: IncreaseFontSize }
  #- { key: Minus,          mods: Control,                         action: DecreaseFontSize }
