#!/bin/bash

clear

extension="${1##*.}"
RED='\033[0;31m'
NC='\033[0m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
case $extension in 
    cpp)
        echo "Starting Auto C++ Runner"
        echo $1 | entr -ps 'clear; echo Compiling C++ File; echo; echo Output:;g++ -o '${1%.cpp}' '$1' && ./'${1%.cpp}
        ;;
    c)
        echo "Starting Auto C Runner"
        echo $1 | entr -ps 'clear; echo Compiling C File; echo; echo Output:;gcc -o '${1%.c}' '$1' && ./'${1%.c}
        ;;
    js)
        echo "Starting Auto JavaScript Runner"
        echo $1 | entr -ps 'clear; echo Compiling JavaScript File; echo; echo Output:;node '$1
        ;;
    py)
        echo "Starting Auto Python Runner"
        echo $1 | entr -ps 'clear; echo Compiling Python File; echo; echo Output:;python '$1
        ;;
    java)
        echo "Starting Auto Java Runner"
        echo $1 | entr -ps 'clear; echo Compiling Java File; echo; echo Output:;javac '$1' && java '${1%.java}
        ;;
    html)
        if pidof -x "firefox" >/dev/null; then
            echo "Starting Auto HTML Runner"
            echo $1 | entr -ps 'clear; echo Rendering HTML File; echo;firefox '$1
        else
            echo -e "${RED}Error${NC} (${LIGHTBLUE}HTML Run${NC}): ${YELLOW}Firefox Needs to Already Be Running${NC}"
        fi
        ;;
    *)
        echo "Unsupported Filetype"
        ;;
esac
