#!/usr/bin/perl
use Term::ANSIColor;
# stats.pl - returns CPU and RAM usage

# RAM stuff

my $total = `grep -e "^MemTotal" -m 1 /proc/meminfo`;
$total =~ s/([^0-9]*)([0-9]*)(.*)$/$2/;

my $available = `grep -e "^MemAvailable" -m 1 /proc/meminfo`;
$available =~ s/([^0-9]*)([0-9]*)(.*)$/$2/;

my $memusage = sprintf("%02d", 100 - ($available / $total * 100));
# printf "RAM: %02d%%\n","$memusage";
my $RAM = "$memusage%";
print "<txt><span fgcolor='#8ec07c'>$RAM</span></txt>";
# weight='Bold'
